services:
  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASS}
    ports:
      - "5433:5432"

  product-db:
    image: postgres:16
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: ${PRODUCT_DB_USER}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASS}
    ports:
      - "5434:5432"

  order-db:
    image: postgres:16
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASS}
    ports:
      - "5435:5432"

  user-service:
    image: faritenrique/user-service:latest
    build: ./user-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://user-db:5432/user_db
      DB_USERNAME: ${USER_DB_USER}
      DB_PASSWORD: ${USER_DB_PASS}
    ports:
      - "8081:8081"
    depends_on:
      - user-db

  product-service:
    image: faritenrique/product-service:latest
    build: ./product-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://product-db:5432/product_db
      DB_USERNAME: ${PRODUCT_DB_USER}
      DB_PASSWORD: ${PRODUCT_DB_PASS}
    ports:
      - "8082:8082"
    depends_on:
      - product-db

  order-service:
    image: faritenrique/order-service:latest
    build: ./order-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://order-db:5432/order_db
      DB_USERNAME: ${ORDER_DB_USER}
      DB_PASSWORD: ${ORDER_DB_PASS}
    ports:
      - "8083:8083"
    depends_on:
      - order-db
